### ISSUE TITLE
You guys didnt even include all the required folders in the source?

### ISSUE THREAD

**Issue by Mxdi** [SirWaddles/JohnWick#2]
![image](https://user-images.githubusercontent.com/43386840/49044015-96ad5680-f19a-11e8-8a01-f5ee0828fc18.png)

**Comment by SirWaddles** [comment]
So originally, there was just the bot and some really basic instructions on how to prepare the assets using UModel, however when Epic added the data-hidden items, the bot needed to be able to decode everything automatically - that's what the `john-wick-extra` package does.

It is a separate package though, and it will likely remain private.

I published the source code so that people can be sure of what the official bot is doing, and the commands it has.

**Comment by NismoGraphics** [comment]
So the bot is useless. Thank you.
